/*
 * js/dom.js
 *
 * 集中管理所有的 DOM 元素获取，避免在多个文件中重复查询。
 */

export const dom = {
    clientIdInput: document.getElementById('clientId'),
    clientSecretInput: document.getElementById('clientSecret'),
    sourceToggleBtn: document.getElementById('sourceToggleBtn'),
    languageToggleBtn: document.getElementById('languageToggleBtn'),
    searchButton: document.getElementById('searchButton'),
    toggleSearchBtn: document.getElementById('toggleSearchBtn'),
    searchCard: document.getElementById('searchCard'),
    usernameInput: document.getElementById('username'),
    searchHistoryContainer: document.getElementById('searchHistoryContainer'),
    loadingDiv: document.getElementById('loading'),
    errorMessageDiv: document.getElementById('errorMessage'),
    playerDataContainer: document.getElementById('playerDataContainer'),
    recentPlaysDiv: document.getElementById('recentPlays'),
    recentPlaysLoader: document.getElementById('recentPlaysLoader'),
    topPlaysDiv: document.getElementById('topPlays'),
    topPlaysAnalysisSection: document.getElementById('topPlaysAnalysisSection'),
    topPlaysSection: document.getElementById('topPlaysSection'),
    recentPlaysSection: document.getElementById('recentPlaysSection'),
    topPlaysSortAndFilterControls: document.getElementById('topPlaysSortAndFilterControls'),
    filteredPpDisplay: document.getElementById('filteredPpDisplay'),
    recentPlaysControls: document.getElementById('recentPlaysControls'),
    recentPpGainDisplay: document.getElementById('recentPpGainDisplay'),
    recentPassOnlyCheckbox: document.getElementById('recentPassOnly'),
    recentBpOnlyCheckbox: document.getElementById('recentBpOnly'),
    recentSelectAllCheckbox: document.getElementById('recentSelectAllCheckbox'),
    recentDownloadSelectedBtn: document.getElementById('recentDownloadSelectedBtn'),
    refreshRecentPlaysBtn: document.getElementById('refreshRecentPlaysBtn'),
    modMatchToggle: document.getElementById('modMatchToggle'),
    selectAllCheckbox: document.getElementById('selectAllCheckbox'),
    downloadSelectedBtn: document.getElementById('downloadSelectedBtn'),
    navLinksContainer: document.getElementById('navLinksContainer'),
    fcFilter: document.getElementById('fcFilter'),
    ppChartStats: document.getElementById('ppChartStats'),
    toast: document.getElementById('toast'),
    keySetupInstructions: document.getElementById('keySetupInstructions'),
    credentialsContainer: document.getElementById('credentialsContainer'),
    keyManagementContainer: document.getElementById('keyManagementContainer'),
    changeKeyBtn: document.getElementById('changeKeyBtn'),
    userSearchArea: document.getElementById('userSearchArea'),
    saveKeysBtn: document.getElementById('saveKeysBtn'),
    player: {
        container: document.getElementById('audioPlayer'),
        audio: document.getElementById('audioElement'),
        info: document.getElementById('player-info'),
        infoText: document.getElementById('player-info-text'),
        playPauseBtn: document.getElementById('player-play-pause-btn'),
        playIcon: document.getElementById('player-play-icon'),
        pauseIcon: document.getElementById('player-pause-icon'),
        progressBar: document.getElementById('player-progress-bar'),
        currentTime: document.getElementById('player-current-time'),
        duration: document.getElementById('player-duration'),
        volumeSlider: document.getElementById('player-volume-slider'),
        closeBtn: document.getElementById('player-close-btn'),
    },
    beatmapSearchPage: {
        page: document.getElementById('beatmapSearchPage'),
        queryInput: document.getElementById('beatmapQueryInput'),
        searchBtn: document.getElementById('beatmapSearchBtn'),
        identifyBtn: document.getElementById('beatmapIdentifyBtn'),
        modeToggleBtn: document.getElementById('beatmapModeToggleBtn'),
        resultsContainer: document.getElementById('beatmapSearchResultsContainer'),
    },    
    playerInfo: {
        banner: document.getElementById('player-banner'),
        profileLink: document.getElementById('playerProfileLink'),
        avatar: document.getElementById('playerAvatar'),
        name: document.getElementById('playerName'),
        flag: document.getElementById('countryFlag'),
        joinDate: document.getElementById('joinDate'),
        level: document.getElementById('playerLevel'),
        pp: document.getElementById('playerPP'),
        accuracy: document.getElementById('playerAccuracy'),
        playcount: document.getElementById('playerPlaycount'),
        playtime: document.getElementById('playerPlaytime'),
        globalRank: document.getElementById('playerGlobalRank'),
        countryRank: document.getElementById('playerCountryRank'),
        rankedScore: document.getElementById('playerRankedScore'),
    },
    ppCalculator: {
        modal: document.getElementById('pp-calculator-modal'),
        card: document.getElementById('pp-calculator-card'),
        title: document.querySelector('#pp-calculator-modal h2'),
        closeBtn: document.getElementById('pp-calc-close-btn'),
        body: document.getElementById('pp-calculator-body'),
        status: document.getElementById('pp-calc-status'),
        content: document.getElementById('pp-calc-content'),
        info: {
            stars: document.getElementById('pp-calc-stars'),
            bpm: document.getElementById('pp-calc-bpm'),
            maxCombo: document.getElementById('pp-calc-max-combo'),
            nObjects: document.getElementById('pp-calc-n-objects'),
            ar: document.getElementById('pp-calc-ar'),
            od: document.getElementById('pp-calc-od'),
            cs: document.getElementById('pp-calc-cs'),
            hp: document.getElementById('pp-calc-hp'),
        },
        pp: {
            display: document.getElementById('pp-calc-pp-display'),
            aim: document.getElementById('pp-calc-pp-aim'),
            speed: document.getElementById('pp-calc-pp-speed'),
            acc: document.getElementById('pp-calc-pp-acc'),
            fl: document.getElementById('pp-calc-pp-fl'),
        },
        controls: {
            lazerCheckbox: document.getElementById('pp-calc-lazer-checkbox'),
            advancedModeCheckbox: document.getElementById('pp-calc-advanced-mode-checkbox'),
            modsContainer: document.getElementById('pp-calc-mods-container'),
            scoreSimContainer: document.getElementById('pp-calc-score-sim-container'),
        }
    }
};

export const chartCanvases = {
   pp: document.getElementById('ppScatterChart').getContext('2d'),
   mapperScatter: document.getElementById('mapperScatterChart').getContext('2d'),
   rank: document.getElementById('rankPieChart').getContext('2d'),
   length: document.getElementById('lengthPieChart').getContext('2d'),
   bpm: document.getElementById('bpmPieChart').getContext('2d'),
   mods: document.getElementById('modsPieChart').getContext('2d'),
};
